[13.0][ADD] fleet_vehicle_history_date_end: Assign end date in vehicle's drivers history
OCA/fleet pull request #1
Opened 2020-05-22 08:05 UTC by mamcode

Odoo only assign the start date on vehicle's drivers history when a new driver is assigned, this module also will assign automatically the end date in previous vehicle's driver histories when a new driver is assigned to the vehicle.

![screenshot-localhost_8099-2020 05 20-21_29_26](https://user-images.githubusercontent.com/334317/82565389-58eb7d00-9b48-11ea-80c6-c45971466edc.png)

2020-05-22 08:49 UTC, ivantodorovich approved these changes
pls squash your commits

2020-05-22 08:51 UTC, ivantodorovich requested changes

2020-05-22 08:51 UTC, ivantodorovich commented on fleet_vehicle_history_date_end/__manifest__.py
> +    "website": "https://www.druidoo.io/",
```suggestion
    "website": "https://github.com/OCA/fleet",
```

2020-05-22 09:29 UTC, mamcode commented
> pls squash your commits

Done.

2020-05-22 13:25 UTC, ivantodorovich approved these changes

2020-06-02 09:04 UTC, mymage commented
Useful improvement.
What do you think about extending date field to date-time, both for start and end? If you have multiple changes in a day (like your example :-) ) and the car gets a contravention it will be easy to find the driver.

2020-06-02 09:09 UTC, mymage approved these changes
Ok for me. And I hope in a near future to be able to write test for my code too.

2020-06-02 12:38 UTC, ivantodorovich commented
/ocabot merge nobump

2020-06-02 12:48 UTC, merged

2020-06-02 14:19 UTC, mamcode commented
> Useful improvement.
> What do you think about extending date field to date-time, both for start and end? If you have multiple changes in a day (like your example :-) ) and the car gets a contravention it will be easy to find the driver.

Hi @mymage thanks for your review :) I believe that your point is interesting and I can agree that it can be useful to have the dates as datetime to have more detail if events occur in the vehicle on the same day to have better traceability in the event that on that same day a vehicle has changed drivers. Maybe you can a PR with this propose and a use case (maybe a unit test).

2020-06-02 22:21 UTC, mymage commented
> Hi @mymage ... PR with this propose and a use case (maybe a unit test)...

Ok I will try the change, but for the UT I don't know were to start. I case I will advise you for help ;-)