[15.0] [MIG] fleet_vehicle_stock: Migration to 15.0
OCA/fleet pull request #104
Opened 2023-03-28 21:05 UTC by rodrigonevest

2023-03-29 22:52 UTC, marcelsavegnago approved these changes

2023-03-29 22:56 UTC, marcelsavegnago requested changes

2023-03-29 22:56 UTC, marcelsavegnago commented on fleet_vehicle_stock/views/fleet_vehicle.xml
> +            <notebook>
I think here we need to define the position inside

2023-03-29 22:57 UTC, marcelsavegnago commented on fleet_vehicle_stock/views/fleet_vehicle.xml
> +            <notebook>
https://github.com/odoo/odoo/blob/15.0/addons/fleet/views/fleet_vehicle_views.xml#L90

2023-03-30 13:26 UTC, marcelsavegnago commented
@rodrigonevest Could you add more tests so that we can increase the test coverage?

2023-04-04 15:04 UTC, ivantodorovich approved these changes

2023-04-04 15:06 UTC, ivantodorovich commented
LG. Thanks!
Let me know if we wait for the unit tests or not ;) 


/ocabot migration fleet_vehicle_stock

2023-04-04 15:14 UTC, marcelsavegnago approved these changes
@ivantodorovich if you can merge, we add more tests at another time.

2023-04-04 15:15 UTC, ivantodorovich commented
/ocabot merge nobump

2023-04-04 15:25 UTC, merged