[15.0][IMP] fleet_vehicle_inspection: Add cost vehicle inspection and create vehicle service
OCA/fleet pull request #133
Opened 2023-12-14 21:27 UTC by carolinafernandez-tecnativa

- Add Cost vehicle inspections. Once is confirmed, service vehicle is created. If inspection is cancelled, service vehicle is deleted.

TT46534

@Tecnativa

2024-01-10 01:28 UTC, marcelsavegnago approved these changes

2024-01-10 06:43 UTC, pilarvargas-tecnativa approved these changes

2024-01-11 12:53 UTC, marcelsavegnago commented
ping @ivantodorovich

2024-01-12 11:41 UTC, ivantodorovich requested changes

2024-01-12 11:41 UTC, ivantodorovich commented on fleet_vehicle_inspection/models/fleet_vehicle_inspection.py
> +        services = records.filtered(lambda rec: rec.service_id).mapped("service_id")
```suggestion
        services = records.service_id
```

💡 tip: This is exactly the same thing, in only 1 step

2024-01-12 11:41 UTC, ivantodorovich commented on fleet_vehicle_inspection/models/fleet_vehicle_inspection.py
> +                .id
```suggestion
```

💡 tip: not needed, you can assign the recordset directly

2024-01-12 11:41 UTC, ivantodorovich commented on fleet_vehicle_inspection/tests/test_fleet_vehicle_inspection.py
> +        with self.assertRaises(UserError):
```suggestion
        with self.assertRaisesRegex(UserError, "Inspection cannot be completed"):
```

💡 tip: Always use `assertRaisesRegex` over `assertRaises`, this way you are sure to be asserting the exact exception you expect. UserErrors can be arised from many different places, and so you risk to be testing something you don't want

⚠️  Also, by the look of the PR diff, it kinda looks like you were expecting a `ValidationError(msg="Must select service type")` here, not a `UserError` 🤔

2024-02-26 15:16 UTC, ivantodorovich approved these changes
/ocabot merge major

2024-02-26 15:20 UTC, merged