[18.0][MIG] fleet_vehicle_calendar_year: Migration to 18.0
OCA/fleet pull request #167
Opened 2024-12-31 11:00 UTC by HeliconiaSolutions

2025-03-05 13:22 UTC, marcelsavegnago approved these changes

2025-04-08 12:16 UTC, BhaveshHeliconia commented
Hey @OCA/fleet-maintainers  would be great if someone could have a look at this module.

2025-04-08 15:24 UTC, ivantodorovich requested changes
/ocabot migration fleet_vehicle_calendar_year

2025-04-08 15:24 UTC, ivantodorovich commented on fleet_vehicle_calendar_year/tests/fleet_vehicle_test.py
> +from odoo.tests.common import TransactionCase
Hey, thanks for trying to improve the module's robustness by writing unit tests.

However here, there's actually no new business logic to test. We don't need to test the ORM core features like actually adding the fields or tracking their changes. We can trust the ORM will do that on its own, as these features are already widely tested in odoo core.

IMO, these tests are not adding any value and thus should be removed

2025-04-09 05:17 UTC, BhaveshHeliconia commented
@ivantodorovich, Please Review.i removed test cases.thanks!

2025-04-09 13:11 UTC, ivantodorovich approved these changes
/ocabot merge nobump

2025-04-09 13:15 UTC, merged