[17.0][MIG] fleet_vehicle_fuel_capacity: Migration to 17.0
OCA/fleet pull request #174
Opened 2024-12-31 13:03 UTC by HeliconiaSolutions

2025-04-15 06:24 UTC, BhaveshHeliconia commented
Hey @OCA/fleet-maintainers would be great if someone could have a look at this module.

2025-04-15 13:02 UTC, marcelsavegnago approved these changes

2025-04-15 14:14 UTC, ivantodorovich requested changes

2025-04-15 14:14 UTC, ivantodorovich commented on fleet_vehicle_fuel_capacity/tests/test_vehicle_fuel_capacity.py
> +        )
These unit tests are not useful.
We should trust the ORM to be able to create records. That's extensibly tested in Odoo core.

2025-04-16 05:51 UTC, BhaveshHeliconia commented
@ivantodorovich, Please Review.it's done.

2025-04-16 10:37 UTC, ivantodorovich approved these changes
Thanks!

/ocabot migration fleet_vehicle_fuel_capacity
/ocabot merge nobump

2025-04-16 10:41 UTC, merged