[17.0][MIG] fleet_vehicle_service_services: Migration to 17.0
OCA/fleet pull request #176
Opened 2024-12-31 13:14 UTC by HeliconiaSolutions

2024-12-31 14:26 UTC, ivantodorovich requested changes

2024-12-31 14:26 UTC, ivantodorovich commented on fleet_vehicle_service_services/tests/test_vehicle_service_services.py
Thanks for the effort in increasing this module robustness.

However, I think these tests aren't useful.
We don't need to write unit tests for every field we add to a model. We can trust the ORM to do its job there, and it's already widely tested by Odoo itself.

IMO we should remove this file

2024-12-31 14:26 UTC, ivantodorovich commented
/ocabot migration fleet_vehicle_service_services

2025-01-01 04:40 UTC, HeliconiaSolutions commented on fleet_vehicle_service_services/tests/test_vehicle_service_services.py
@ivantodorovich , Thanks for the suggestions.it's fixed.

2025-02-27 11:42 UTC, HeliconiaSolutions commented
@ivantodorovich, Please Review.

2025-03-05 13:25 UTC, marcelsavegnago approved these changes

2025-04-08 12:15 UTC, BhaveshHeliconia commented
Hey @OCA/fleet-maintainers when you get a chance, kindly review and consider merging it.

2025-04-08 15:17 UTC, ivantodorovich approved these changes
/ocabot merge nobump

2025-04-08 15:20 UTC, merged