[13.0][ADD] fleet_vehicle_license_plate_alt: Alternative license plate for vehicles
OCA/fleet pull request #2
Opened 2020-05-22 08:11 UTC by mamcode

![screenshot-localhost_8099-2020 05 21-11_17_43](https://user-images.githubusercontent.com/334317/82575338-598b1000-9b56-11ea-9325-03e8dcc9a6ea.png)

2020-05-22 08:50 UTC, ivantodorovich approved these changes
pls squash your commits

2020-05-22 08:50 UTC, ivantodorovich requested changes

2020-05-22 08:50 UTC, ivantodorovich commented on fleet_vehicle_license_plate_alt/__manifest__.py
> +    "website": "https://www.druidoo.io/",
```suggestion
    "website": "https://github.com/OCA/fleet",
```

2020-05-22 09:21 UTC, mamcode commented
> pls squash your commits

Done.

2020-05-22 13:24 UTC, ivantodorovich approved these changes

2020-06-02 11:53 UTC, mymage approved these changes
Only a suggestion to do label more readable.

2020-06-02 11:53 UTC, mymage commented on fleet_vehicle_license_plate_alt/models/fleet_vehicle.py
> +    license_plate_alt = fields.Char(
```suggestion
    license_plate_alt = fields.Char("Alternative Licence Plate",
```

2020-06-02 13:26 UTC, ivantodorovich commented
seems pre-commit is failing on that last commit.
In any case, can you pls squash them ?

2020-06-02 14:02 UTC, mamcode commented
> seems pre-commit is failing on that last commit.
> In any case, can you pls squash them ?

Done :)

2020-06-02 14:17 UTC, ivantodorovich commented
/ocabot merge nobump

2020-06-02 14:23 UTC, merged